### ISSUE TITLE
Make zstd compressionLevel configurable 

### ISSUE THREAD

**Issue by shangxinli** [airlift/aircompressor#107]
Current ZstdCompressor hardcode the compressionLevel as CompressionParameters.DEFAULT_COMPRESSION_LEVEL.  It needs to be configuable.

**Comment by glukasiknuro** [comment]
Other levels are not supported, see https://github.com/airlift/aircompressor/issues/99

**Comment by findepi** [comment]
@glukasiknuro thanks for linking the two.

Closing in favor of https://github.com/airlift/aircompressor/issues/99.
