### ISSUE TITLE
Zstd Hadoop compression codec?

### ISSUE THREAD

**Issue by vvvvalvalval** [airlift/aircompressor#109]
AFAICT, there is no Hadoop codec for Zstd in this library, despite what the README says, is this correct?

**Comment by syed72** [comment]
Any idea, when Zstd Hadoop compression codec will be released?

**Comment by findepi** [comment]
To the best of my knowledge no-one is currently working on it.
In [Presto](https://github.com/prestosql/presto/) we use ZSTD compressor directly.

**Comment by electrum** [comment]
@Praveen2112 is working on this.

**Comment by dain** [comment]
This was implemented in #152
