### ISSUE TITLE
Streaming compression/decompression for Zstd

### ISSUE THREAD

**Issue by vkrevs** [airlift/aircompressor#112]
Hi. Is there support for Zstd streaming compression/decompression in this library (like in native zstd's streaming_compression/streaming_decompression examples)?

If not, can you mark this as an enhancement request please?

**Comment by rrva** [comment]
I was looking for this as well, based on InputStream / Outputstream

**Comment by tomdcc** [comment]
+1 was looking for a drop-in replacement for the streams in zstd-jni (and most other compression libs, tbh).
