### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by bolds07** [airlift/aircompressor#123]
Is it made for working on android devices?

I'm getting 

` java.lang.NoSuchFieldError: No static field ARRAY_BYTE_BASE_OFFSET of type I in class Lsun/misc/Unsafe; or its superclasses (declaration of 'sun.misc.Unsafe' appears in /apex/com.android.art/javalib/core-oj.jar)`

**Comment by dain** [comment]
Supporting Android is beyoned the scope of this project.

**Comment by Cyberavater** [comment]
This is because Android is a little-endian platform and doesn't have `sun.misc.Unsafe` included in the SDK.

It is possible to use unsafe in Android using third-party libraries but that most likely will require some modification in this lib too.

**Comment by alesimula** [comment]
Just in case anyone's looking for an Android compatible fork: https://github.com/alesimula/murine-aircompressor
