### ISSUE TITLE
ZstdCompressor OutputStream and InputStream

### ISSUE THREAD

**Issue by jackluo923** [airlift/aircompressor#138]
Similar to zstd-jni and apache commons libraries, they offer OuputStream and InputStream classes for zstd compression. This issue is similar to the enhancement feature request brought up in 2020 from [issue 112](https://github.com/airlift/aircompressor/issues/112). Would this project welcome this contribution now or have the authors already have this feature implemented but not released? If it's the former, I am happy to contribute this functionality to this project.

**Comment by wetneb** [comment]
According to [this comment](https://github.com/airlift/aircompressor/issues/137#issuecomment-1032945121) it looks like your contribution would be welcome. Many people seem to be interested in this, so if for some reason your PR does not end up being merged and released, that might be enough momentum for a friendly fork already… so just go ahead!

**Comment by jonmv** [comment]
This would be great!

**Comment by bondolo** [comment]
This would appear to be resolved in #152

**Comment by tburch** [comment]
➕ to having this functionality!

**Comment by dain** [comment]
Fied in #152
