### ISSUE TITLE
Add `SECURITY.md` file and enable vulnerability reporting

### ISSUE THREAD

**Issue by Marcono1234** [airlift/aircompressor#176]
Hello,
could you please add a [`SECURITY.md`](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) file to your repository, and ideally also enable [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)?

**Comment by Marcono1234** [comment]
@dain and @electrum, could you please have a look at this?

Also @dain, because https://github.com/dain/snappy now refers to this repository here and because snappy is archived and I cannot comment there anymore, should a CVE be requested for https://github.com/dain/snappy/issues/20? Because if users decompress untrusted data, this could be abused for a denial of service attack by crashing the JVM.
The CVE would also have the side-effect of informing users that the repository is not maintained anymore.

**Comment by martint** [comment]
I've enabled private vulnerability reporting.
