### ISSUE TITLE
Remove dependency on sun.misc.Unsafe?

### ISSUE THREAD

**Issue by javafanboy** [airlift/aircompressor#179]
As I understand it sun.misc.Unsafe is removed in JDK17 and later - I wonder if there is any plans to remove the use of this class in air compressor allowing it to be used with also the latest JDKs?

**Comment by dain** [comment]
Unsafe is still in the JVM (we are using 21), so this still works.  That said, there is only limited unsafe usage in the newer versions, and we'd like to remove the last bits once the equivilent APIs are added to Java.  This is described in the readme her https://github.com/airlift/slice#unsafe-usage
