### ISSUE TITLE
May I ask if Android is usable？

### ISSUE THREAD

**Issue by darrenjh** [airlift/aircompressor#180]
Hello, may I ask if Android can use this library? Which version of the corresponding main library does this correspond to?

**Comment by dain** [comment]
FWIU Android does not have `sun.misc.Unsafe`, and this codebase makes extensive use of this.

**Comment by alesimula** [comment]
@dain Android [does have sun.misc.Unsafe](https://android.googlesource.com/platform/libcore/+/refs/heads/oreo-release/ojluni/src/main/java/sun/misc/Unsafe.java), it just doesn't have copyMemory(Object, long, Object, long, long), and some static fields like ARRAY_BYTE_BASE_OFFSET in it, I've created an Android 8.0+ compatible fork of version 2 here (+ some stuff):

https://github.com/alesimula/murine-aircompressor
