### ISSUE TITLE
java 9 illegal reflective access waring

### ISSUE THREAD

**Issue by brackxm** [airlift/aircompressor#75]
warning on java 9:
(probably known as the class is called UnsafeUtil)

`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.airlift.compress.snappy.UnsafeUtil (.../repository/io/airlift/aircompressor/0.9/aircompressor-0.9.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.airlift.compress.snappy.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

**Comment by dain** [comment]
High performance compression implementations are not possible without Unsafe.  This library should continue to work in the future, and we continue to work with the JVM maintainers to try to find a safe method to obtain the same performance as Unsafe.
