### ISSUE TITLE
.git directory could not be found

### ISSUE THREAD

**Issue by amerolla** [airlift/aircompressor#84]
I'm getting this error when I try to build:
Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (default) on project aircompressor: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml

**Comment by dain** [comment]
I think you need to build from a full git checkout, which will contain a `.git` directory.

**Comment by dain** [comment]
Clone the repository from github instead of downloading the tar.

**Comment by amerolla** [comment]
That worked! Thanks Dain.

**Comment by amerolla** [comment]
Thank you Dain. That did it.

**Comment by amerolla** [comment]
Hey Dain,

Can you point me to any documentation on how to run these benchmarks?

Thanks very much.

**Comment by dain** [comment]
I normally run them from the IDE.  @martint do you have the CLI command to run the benchmarks handy?

**Comment by martint** [comment]
You can run from the CLI like this:

```
mvn exec:exec -Dexec.classpathScope=test -Dexec.executable="$JAVA_HOME/bin/java" -Dexec.args="-XX:+UseG1GC -cp %classpath io.airlift.compress.benchmark.CompressionBenchmark -p algorithm=airlift_lz4 -i 20 -wi 20 -f 10"
```

The options after CompressionBenchmark are standard JMH args, so adjust as necessary to control paramenters, warmup/measurement iterations, etc.
