### ISSUE TITLE
Configurable compression level in ZstdCompressor

### ISSUE THREAD

**Issue by waypoint100** [airlift/aircompressor#99]
That would be very helpful

**Comment by glukasiknuro** [comment]
It looks like only level 3 is implemented in aircompressor (possibly levels 2 and 4 for some particular file sizes), see https://github.com/airlift/aircompressor/blob/24b4f18dcb8a70d273ba1d1cd4c0715f15909573/src/main/java/io/airlift/compress/zstd/CompressionParameters.java#L152

**Comment by dain** [comment]
Only the default level is supported right now, so it doesn’t make sense to allow it to be configurable at this time
